---
abstract: 'There is Brik for that.'
author:
  - 'GomoR <gomor_at_metabrik.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Metabrik
no_index:
  directory:
    - t
    - inc
requires:
  Class::Gomor: '0'
  Cwd: '0'
  Data::Dump: '0'
  File::Find: '0'
  File::HomeDir: '0'
  IO::All: '0'
  Lexical::Persistence: '0'
  Module::Reload: '0'
  Term::ANSIColor: '0'
  Term::Shell: '0'
  local::lib: '0'
version: '1.01'
